### PR TITLE
Misc. RPC related updates

### PR DESCRIPTION
**Pull request by dexX7**
First half of commits is due to the upstream merge.

Actual diff:
- https://github.com/dexX7/bitcoin/compare/f425e8644874f1d7769b4f126292a01213f9e93f...dexX7:oc-0.10-rpc-checks-objects

### CODE REVIEW

**Comment by dexX7** [comment]
Argh, rebasing broke the signatures of the first half.

This probably creates chaos, if merged. I'd resubmit [the actual diff](https://github.com/dexX7/bitcoin/compare/f425e8644874f1d7769b4f126292a01213f9e93f...dexX7:oc-0.10-rpc-checks-objects), after the RPC branch is up to date, if this is of use for you.. :)

**Comment by zathras-crypto** [comment]
Would it be easier for me to just merge from upstream mate?

**Comment by dexX7** [comment]
Yes. Then I could rebase on top of the updated branch, and everything is in order again. :)

**Comment by zathras-crypto** [comment]
Sure, sure, let me push :)

**Pull request closed without merging**
