### PR TITLE
Resolve merge conflicts after meta DEx RPC enabler PR

### PR DESCRIPTION
**Pull request by dexX7**
https://github.com/OmniLayer/omnicore/pull/8 touched some parts, which caused merge conflicts for this branch.

### CODE REVIEW

**Comment by dexX7** [comment]
Not yet finished. One moment..

**Comment by dexX7** [comment]
Alright. This seems to do it, even though you may just pull the updated omnicore-0.0.10 branch in yourself. For an easier comparison, the actual merge conflicts can be addressed by the changes of the following commit: https://github.com/dexX7/bitcoin/commit/23f8791a9be6dbf1580e959f1d3fffaa3e5b6927  - ... though cherry-picking this one alone doesn't seem to do the trick, because `trade_MP` for example was moved somewhere inbetween.

Sorry for the trouble!

**Comment by zathras-crypto** [comment]
No trouble at all :)

**Comment by zathras-crypto** [comment]
Just a quick one to note test plan for MetaDEx passes so likely test plan is insufficient.

The UI throws up examples that are easy to spot, for example:
image

There should be matching going on here.  Dumping the MetaDEx state we can pluck out a couple of offers that clearly should have been matched/traded:

```
0.20000000000000000000000000000000000000000000000000= 5.00000000000000000000000000000000000000000000000000:mpZATHupfCLqet5N1YL48ByCM1ZBfddbGJ in 311791/028, txid: ee5272132f , trade #1 2.00000000 for #12 10.00000000
5.00000000000000000000000000000000000000000000000000= 0.20000000000000000000000000000000000000000000000000:mpZATHupfCLqet5N1YL48ByCM1ZBfddbGJ in 306354/005, txid: 9572150174 , trade #12 91.00000000 for #1 18.20000000
```

Note they're the same address but this is permitted (quoting spec)

> The protocol then finds existing sell orders that qualify (match), possibly including existing sell orders from that same address.

I'm itching to get into the nuts and bolts of MetaDEx but am really trying to get through the work I've been assigned first (which I think is getting there) so sorry I'm not being much help with specifics - figured it's best to note these things even if it's just for myself when I can circle back round to it :)

**Comment by dexX7** [comment]
Well, this was sort of expected.. :) I suggest you keep posting any flaws you find, and pin down the underlying issue (or issues).

**Comment by dexX7** [comment]
I'm confused. A unit price of 20'000'000? Shouldn't it be 0.2 TMSC? Sold 10x IndivisibleToken for 0.2 TMSC each (= 2.0 TMSC total).

dex_issues

**Comment by zathras-crypto** [comment]
Clearly something wrong there
image

**Comment by zathras-crypto** [comment]
Note listing sells via the UI is likely still broken (I haven't looked at refreshing sendTrade() from the old stuff from Dec14 yet)

**Comment by zathras-crypto** [comment]
Oh, you're in regtest mode nevermind hehe

**Comment by zathras-crypto** [comment]
Just sent the same transaction from the UI on testnet, 10 indivisible tokens for 0.2 each - looks OK in pending, will see what happens when it confirms:
image

**Comment by zathras-crypto** [comment]
Ahh nevermind, I thought I'd got all the divisibility display bugs out yesterday but seems a couple still remain... Working on it..

**Comment by dexX7** [comment]
Hehe, at some point you'll probably look back and wonder: "why didn't I use regtestnet earlier?" :)

Todo note to myself: tutorial for spock + some basic, manual regtest stuff.

**Comment by zathras-crypto** [comment]
> at some point you'll probably look back and wonder: "why didn't I use regtestnet earlier?"

Hehe I have no doubt mate, I have no doubt :)

Think https://github.com/zathras-crypto/mastercore/commit/0f5baed3f4faacdbf6c9a3aba44cf62d25a4c349 should sort that price display issue mate.

**Pull request merged**
