### PR TITLE
Application: isolate and replace version and build information

### PR DESCRIPTION
**Pull request by dexX7**
Starting with the most controversial change, which may need further input or refinement:
1. The version and build information are no longer done inline with support of `version.cpp/.h`, but "in house" within `mastercore_version.cpp/.h`, which is now almost a copy of `version.cpp`. This was done for two reasons: a) reset `version.cpp/.h` to it's original state, but more relevant: b) to cover all cases. While the commit information was available for "standard" builds, the old version did not cover the case where a release is exported, e.g. via Gitian building.
2. It replaces the use of variables with methods such as `OmniCoreVersion()` and `BuildCommit()`. It does not have to be this way, but it appeared more suitable.
3. There is `OmniCoreVersion()`, which returns for example `"0.0.9.1-dev"` and `OmniCoreRelease()`, which currently returns `"Experimental UI 0.0.9.1-dev"`. The later is used in the splash screen and help message text for `mastercore-qt`. The function names might not be intuitive, and something like `OmniCoreVersionLong()` might be more appropriate. Input on this is very welcomed.
4. Probably less controversial are the other changes: further rebranding of `"Bitcoin"`, `"Bitcoin Core"`, `"Omnicore"` to `"Omni Core"`.

Example old:
version_pr_old

Example updated:
version_pr_new

### CODE REVIEW

**Comment by zathras-crypto** [comment]
Thanks for the submission, will review once we're through on transaction history.

**Comment by zathras-crypto** [comment]
Looks ok from a quick review :)

3) Perhaps OmniCoreVersion() and OmniCoreUIVersion() would be appropriate?

**Comment by dexX7** [comment]
Haha yeah, I don't know. At first I named it `OmniCoreSplashScreenLabel()`, which is similar to `OmniCoreUIVersion()`, but this seemed wrong, as the name should not describe where it's used, but rather what it is.

The Bitcoin Core sort-of-equivalent is `FormatFullVersion()`, which doesn't seem to be perfect either, but we basically have a short version `"0.0.9.1"` and the long version with `"Experimental UI 0.0.9.1"`. Something like `OmniCoreVersionWithDescriptionPrefix()` would be down to the point, but ... hehe.

I'd be more than happy to rename it though, and other proposals are more than welcomed. :)

**Comment by zathras-crypto** [comment]
TBH I just don't like the idea of having something like 'Experimental UI' floating around in a variable it's not clear is just for the UI (eg calling it `OmniCoreVersionWithDescriptionPrefix()` we'd then need to somehow explain that this is not appropriate to be used in the daemon etc).

Hope that makes sense!

**Comment by dexX7** [comment]
> just for the UI

Oh, this is the case? It _is_ intended for the UI? I actually assumed this is just some.. well, release name or so, which might as well be returned by `getinfo_MP` etc.

**Comment by zathras-crypto** [comment]
Well there was never previously a variable for it IIRC - long story short I wanted to keep our versioning intact (eg `0.0.9.1-dev`, `0.0.9.1-rc1`, `0.0.9.1-rel` for example) but wanted some way to let the user know that the UI component was very experimental.  IIRC I just prepended the version on splash with a string "Experimental UI" originally...

**Comment by dexX7** [comment]
Ahh I see.

At the beginning there were hardcoded labels such as `"Experimental UI Alpha 0.0001"`. I used the "long" version also in the "about" dialog, as well as the help message for `mastercore-qt --help`, as shown in the screenshot above.

Edit: in the case no `OMNICORE_RELEASE_NAME` is defined, `OmniCoreRelease()` returns `"Version 0.0.9.1"`.

**Comment by dexX7** [comment]
@zathras-crypto: do I read you correctly that I should remove `OMNICORE_RELEASE_NAME` and `OmniCoreRelease()` and use `OmniCoreVersion()` where `OmniCoreRelease()` was used?

In the "About Omni Core` dialog it could then show:

```
Omni Core version 0.0.9.1-dev (64-bit)
```

... instead of:

```
Omni Core Experimental UI 0.0.9.1-dev (64-bit)
```

And `mastercore-qt --help` could show:

```
~/Projects/Cpp/mastercore$ mastercore-qt --help
Omni Core v0.0.9.1-dev                                        << with "v" prefix?
Bitcoin Core v0.9.3.0-654be55-beta

Usage:
  mastercore-qt [command-line options]
```

... instead of:

```
~/Projects/Cpp/mastercore$ mastercore-qt --help
Omni Core Experimental UI 0.0.9.1-dev
Bitcoin Core v0.9.3.0-654be55-beta

Usage:
  mastercore-qt [command-line options]
```

Right now, without this PR, it returns:

```
~/Projects/Cpp/mastercore$ mastercore-qt --help
Omni Core version v0.9.3.0-654be55-beta

Usage:
  bitcoin-qt [command-line options]
```

**Comment by zathras-crypto** [comment]
Perhaps I can clarify.  Unless at some future point we decouple the UI from the daemon, then I prefer to keep a single version {string|label|message|whatever}.  0.0.9.1 whilst 95% of the changes are to the UI, some changes (eg bugfixes) are still made to the shared code affecting both daemon and UI.  Thus I prefer to think of daemon/UI as a package, and 0.0.9.1 represents that package.

The concept of a release name is an interesting one (eg would you be proposing that in 0.0.10 "Experimental UI" is replaced with "MetaDEx Live" or similar?).  If so that wasn't my intention when I originally added "Experimental UI" to the splash screen - it wasn't meant to denote a release name, simply to make sure users (who often skip warnings without reading them) understood that the UI was very experimental (thankfully with your help it's decidedly less experimental these days however).

I guess simplified, "Experimental UI" was just a label on the splash to make sure users knew that it was experimental, I hadn't envisaged it being used anywhere else.

My own personal preference is for:

> And mastercore-qt --help could show:

```
~/Projects/Cpp/mastercore$ mastercore-qt --help
Omni Core v0.0.9.1-dev                                        << with "v" prefix? Yes :)
Bitcoin Core v0.9.3.0-654be55-beta
```

I'd prefer not to have:

```
~/Projects/Cpp/mastercore$ mastercore-qt --help
Omni Core Experimental UI 0.0.9.1-dev
Bitcoin Core v0.9.3.0-654be55-beta
```

If we are to go in a release name direction (which I'm not against) I believe we should append that in brackets, to use an example:
`mkvmerge v2.0.2 ('You're My Flame') built on Feb 21 2007 23:40:55`

EDIT: 

> Right now, without this PR, it returns:

Well that's not cool and obviously yep needs changing :)

**Comment by dexX7** [comment]
> eg would you be proposing that in 0.0.10 "Experimental UI" is replaced with "MetaDEx Live" or similar?

This was my understanding of "Experimental UI" at least, but I have not really an opinion on whether this is useful or not. More relevant in my opinion would be to have the ability to know whether a version breaks consensus or if it could be skipped.

I updated the PR to reflect the points mentioned above, in particular:
- removed `OmniCoreRelease()` and `OMNICORE_RELEASE_NAME`
- hardcoded the splash screen label to `"Experimental UI " + OmniCoreVersion()`

The relevant parts to know:
- `mastercore_version.h` is the place to go to update Omni Core version related information
- `BitcoinCoreVersion()` returns the string `"0.9.3"`
- `OmniCoreVersion()` returns the string `"0.0.9.1-dev"`
- `BuildDate()` returns a string with the build date
- `BuildCommit()` returns a string with the commit identifier

The rest is further rebrand to "Omni Core", e.g. in the "about" dialog, "mastercore-qt --help" result, ...

**Comment by dexX7** [comment]
Hehe sorry for the back and forth. I removed all "rebrand" changes from this PR, so this one is solely focused on the "version" stuff.

**Comment by zathras-crypto** [comment]
Looks OK to merge, is this final now?

Also if we can let's try and note any functional impact (eg in this case 'old style' alert messages using `91` etc for version check would no longer work and need to use the new version calculation model:

```
static const int OMNICORE_VERSION =
                        +  100000 * OMNICORE_VERSION_MAJOR
                        +     100 * OMNICORE_VERSION_MINOR
                        +       1 * OMNICORE_VERSION_PATCH;
```

Not so much an issue for now, but later when documentation exists for this type of stuff it'll be easier to know what needs updating and such.

Thanks :)
Z

**Comment by dexX7** [comment]
Yes, I consider it as final.

`OMNICORE_VERSION` was really close. The additional filling with zeros is intended to be ready to deal with version numbers >10, which seemed nice to have, but not strictly required. The reason I did include it in the end was because it is backwards compatible in the context of the alert system.

The relevant check is `if (OMNICORE_VERSION_BASE > expiryValue)` and to avoid screwing up, a new version must be greater than an old version, which is given in this case, namely `900100 > 90`.

But just to be clear, this also introduces a third version part `"OMNICORE_VERSION_PATCH"`, which is currently unused (= 0).

You're totally right though, changes here have consequences for the future, so it should be done right. Does the above sounds reasonable, especially in the context of introducing the "patch" part?

**Comment by zathras-crypto** [comment]
> backwards compatible in the context of the alert system.

In code yes, but my point was more about process - the only reason it even popped into my head is because while I was reviewing I realized the notes I gave to a certain few (auth'd alert senders) would no longer be valid (as they state to send an alert with for example 92 to outdate a 0.0.9.1 version & that would just be immediately expired under the new numbering scheme).

Hence while thinking about updating said notes I thought I'd mention (for me as much as anyone else) to highlight functional changes so we don't miss updating respective info.  Hope that clarifies what I was thinking there :)

The `OMNICORE_VERSION_PATCH` is probably the right way to go, I'd always just assumed we'd increase the minor for anything we tagged but the extra patch version gives us extra flexibility (ie a more granular versioning scheme).

Yep definitely sounds reasonable :)

**Comment by dexX7** [comment]
> In code yes, ...
> 
> Hence while thinking about updating said notes I thought I'd mention (for me as much as anyone else) to highlight functional changes so we don't miss updating respective info. Hope that clarifies what I was thinking there :)

Makes a lot of sense. This is something I didn't consider. All this should probably be properly documented - rather sooner than later.

**Pull request merged**
