### PR TITLE
Transactions: support and use client data carrier size

### PR DESCRIPTION
**Pull request by dexX7**
The original commit: https://github.com/bitcoin/bitcoin/commit/2aa632921efd861a7c9968e8faf6c73cb3d62c4a

### CODE REVIEW

**Comment by dexX7** [comment]
Just in case, depending on when the transition to 0.10 happens.

**Comment by zathras-crypto** [comment]
Ah - TYVM :)

**Comment by dexX7** [comment]
Ah and FYI: http://bitwatch.co/uploads/0.0.9.2-op-return-settings/ :)

Looks very good!

**Comment by zathras-crypto** [comment]
Nice :) thanks for running those :)

**Pull request merged**
